"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Generated by CoffeeScript 2.0.0
var autoLink = exports.autoLink = function autoLink(str) {
  var callback, k, linkAttributes, option, pattern, v;
  pattern = /(^|[\s\n]|<[A-Za-z]*\/?>)((?:https?|ftp):\/\/[\-A-Z0-9+\u0026\u2019@#\/%?=()~_|!:,.;]*[\-A-Z0-9+\u0026@#\/%=~()_|])/gi; // Capture the beginning of string or line or leading whitespace
  // Look for a valid URL protocol (non-captured)
  // Valid URL characters (any number of times)
  // String must end in a valid URL character
  if (!((arguments.length <= 1 ? 0 : arguments.length - 1) > 0)) {
    return str.replace(pattern, "$1<a href='$2'>$2</a>");
  }
  option = arguments.length <= 1 ? undefined : arguments[1];
  callback = option["callback"];
  linkAttributes = function () {
    var results;
    results = [];
    for (k in option) {
      v = option[k];
      if (k !== 'callback') {
        results.push(" " + k + "='" + v + "'");
      }
    }
    return results;
  }().join('');
  return str.replace(pattern, function (match, space, url) {
    var link;
    link = (typeof callback === "function" ? callback(url) : void 0) || "<a href='" + url + "'" + linkAttributes + ">" + url + "</a>";
    return "" + space + link;
  });
};
//# sourceMappingURL=autolink.js.map
